### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by liu-600** [NJUPT-MCC/Self-PT#1]
Hi, I would like to express my appreciation for your excellent work, which has greatly benefited me. 
However, I encountered an issue while trying to download the dataset using the provided link. The images are in .csv format instead of .h5, which does not match the expected format in the code, resulting in an inability to run it.
I kindly request if it would be possible for you to provide the dataset in .h5 format or guide me on how to handle the .csv format appropriately. Thank you in advance for your assistance.

**Comment by yuanrr** [comment]
Hi @liu-600, we greatly appreciate your interest in our work. 

We are very sorry for our negligence that led to such a problem. We used the same processing method as VL-T5, which can be found at https://github.com/j-min/VL-T5/tree/main/feature_extraction.

Hope this is useful for you, and if possible, we will find a way to provide .h5 files.

**Comment by liu-600** [comment]
Thank you for your response. I have found a solution for converting TSV to H5 format, and the problem has been successfully resolved. I appreciate your assistance in this matter.
